### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by HrithikMittal** [dhmlau/loopback4-example-todo-jwt#1]
Your code for authentication is working but can you add authorization into it. Role-based access control.

**Comment by dhmlau** [comment]
It's my next project to add authorization :)
In the meanwhile, did you get the chance to look at the shopping example? https://github.com/strongloop/loopback4-example-shopping.

**Comment by HrithikMittal** [comment]
Okay I will wait because I try shopping example it is too tough to understand but your repos are very good source for understanding and implementing thank you.

**Comment by HrithikMittal** [comment]
Hello @dhmlau I implement the Authorization Check it out https://github.com/HrithikMittal/loopback4-authorization 
and give your feedback on what else can be improved? and also check the Readme where I mentioned all the steps to implement Role-based Acces control.
